Repository OffchainLabs/go-ethereum, pull requests merged in 2024-12, with the labels that each got.

#379 Merge v1.14.3
  .travis.yml
  params/version.go
Labels: design-approved

#386 Revert accidental change to tipReceipient
  core/state_transition.go
Labels: s, design-approved

#387 Fix deterministic flag in geth v1.14.4 merge
  arbitrum/recordingdb.go
  core/state/statedb.go
Labels: s

#376 add SyncMode option to PebbleExtraOptions
  ethdb/pebble/extraoptions.go
  ethdb/pebble/pebble.go
Labels: s, design-approved

#389 Include tx compression level in calldata units cache
  core/types/transaction.go
  core/types/transaction_arbitrum_test.go
Labels: s, design-approved

#388 [NIT-1285] Consolidate ArbOS version constants into a single file
  params/config.go
  params/config_arbitrum.go
  params/config_test.go
Labels: s, design-approved

#377 Filter transaction
  core/state/statedb.go
  core/state/statedb_arbitrum.go
  core/vm/interface.go
Labels: s, design-approved

#372 Add Clear method to SizeConstrainedCache
  common/lru/blob_lru.go
Labels: s, design-approved

#385 Remove unused BlockHashOp
  core/vm/instructions_arbitrum.go
Labels: s, design-approved
