Repository OffchainLabs/go-ethereum, pull requests merged in 2024-07, with the labels that each got.

#333 Add ArbosVersion_StylusFixes
  params/config_arbitrum.go
Labels: s, design-approved

#336 Only run "design approved" check when necessary
  .github/workflows/go.yml
  .github/workflows/merge-checks.yml
Labels: s, design-approved

#332 Don't double fetch header in DoEstimateGas
  internal/ethapi/api.go
Labels: s, design-approved

#338 Switch merge checks action to pull_request_target event
  .github/workflows/merge-checks.yml
Labels: s

#335 [NIT-1168] Metrics for total gas used for eth_call and total gas used for eth_estimateGas
  internal/ethapi/api.go
Labels: s, design-approved

#341 [NIT-2671] Merge v1.13.14
  cmd/clef/README.md
  core/txpool/blobpool/blobpool.go
  core/txpool/blobpool/blobpool_test.go
  core/txpool/blobpool/config.go
  core/txpool/errors.go
  core/txpool/legacypool/journal.go
  core/txpool/txpool.go
  core/txpool/validation.go
  eth/catalyst/api.go
  eth/catalyst/api_test.go
  eth/tracers/native/call.go
  internal/ethapi/api.go
  internal/ethapi/transaction_args.go
  log/logger_test.go
  p2p/server.go
  p2p/transport.go
  params/version.go
  rpc/types.go
Labels: design-approved

#342 [NIT-2672] Merge v1.13.15
  .github/workflows/ci.yml
  core/rawdb/accessors_chain.go
  core/state/snapshot/conversion.go
  core/state/statedb.go
  eth/filters/api.go
  eth/protocols/snap/gentrie.go
  eth/protocols/snap/gentrie_test.go
  eth/protocols/snap/metrics.go
  eth/protocols/snap/progress_test.go
  eth/protocols/snap/sync.go
  internal/testrand/rand.go
  params/version.go
  trie/stacktrie.go
  trie/stacktrie_fuzzer_test.go
  trie/stacktrie_test.go
  trie/trie_test.go
Labels: design-approved
