Repository OffchainLabs/go-ethereum, pull requests merged in 2025-01, with the labels that each got.

#393 fix flatCallTracer onexit out of bound
  eth/tracers/native/call_flat.go
Labels: s, design-approved

#394 backport #393 to nitro v3.3.x - fix flatCallTracer onexit out of bound
  eth/tracers/api_test.go
  eth/tracers/native/call_flat.go
Labels: s

#396 Don't modify gas cap if already zero (infinite)
  internal/ethapi/transaction_args.go
Labels: s, design-approved

#397 Improves triedb metrics
  triedb/hashdb/database.go
Labels: s, design-approved

#398 Flush triedb function
  core/blockchain.go
  core/blockchain_arbitrum.go
Labels: s, design-approved

#399 Optimize destroying an account with no storage in snapshot diffToDisk
  core/state/snapshot/disklayer.go
  core/state/snapshot/snapshot.go
Labels: s, design-approved

#400 Fixes mutex in FlushTrieDB
  core/blockchain_arbitrum.go
Labels: s, design-approved

#401 eth/tracers: fix basefee context for traceBlock (#29811)
  eth/tracers/api.go
  eth/tracers/api_test.go
Labels: design-approved

#369 Add a boolean field to tx receipt object indicating if the tx was timeboosted
  arbitrum/apibackend.go
  common/types.go
  eth/api_backend.go
  internal/ethapi/api.go
  internal/ethapi/api_test.go
  internal/ethapi/backend.go
  internal/ethapi/transaction_args_test.go
Labels: s, design-approved
