Repository OffchainLabs/go-ethereum, pull requests merged in 2025-05, with the labels that each got.

#448 Avoid overflow when adding additional gas
  internal/ethapi/api.go
Labels: s, design-approved

#450 arb chain config: NativeTokenOwnersEnabledFrom
  params/config.go
  params/config_arbitrum.go
Labels: s

#456 Revert setFeeDefaults to original code from geth
  internal/ethapi/transaction_args.go
Labels: s, design-approved

#447 ArbOS 41: Changes related to Mint and Burn native token
  core/genesis.go
  core/state/statedb.go
  core/state/statedb_hooked.go
  core/tracing/gen_balance_change_reason_stringer.go
  core/tracing/hooks.go
  core/types/arbitrum_signer.go
  core/vm/interface.go
  params/config.go
  params/config_arbitrum.go
Labels: s, design-approved

#453 Export `filterLogs` function from eth/filters package for usage in nitro
  eth/filters/filter.go
  eth/filters/filter_system.go
Labels: s, design-approved

#460 Avoid overflow when adding postingGas
  internal/ethapi/transaction_args.go
Labels: design-approved

#462 Update the fixtures_pextra-devnet-6.tar.gz checksum
  build/checksums.txt
Labels: s, design-approved

#455 Handle gas pool overflow gracefully
  internal/ethapi/api.go
Labels: s, design-approved
